### ISSUE TITLE
Improve distance and speed unit handling

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#234]
Geopy provides a Distance class that makes it easy to switch between distance units: m, km, miles, feet, nautical:

https://github.com/geopy/geopy/blob/40717e64e9a79ab52ecbf39530f7c5d663c5d664/geopy/distance.py#L190

MovingPandas should have similar additional capabilities for speed: m/s, ft/s, km/h, mph, knot

**Comment by raybellwaves** [comment]
Interesting. I've used https://github.com/hgrecco/pint-pandas for unit conversion. Given geopy is a requirement makes sense to use that.

**Comment by bamacgabhann** [comment]
I have working code for this now, I need to check over it and tidy things up but hoping to submit a pull request soon.
