### ISSUE TITLE
Clip fails for Polygons with holes and Multipolygons in edge cases

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#236]
As reported in #235:

![image](https://user-images.githubusercontent.com/590385/182443876-4b173eac-a51c-42cf-bad7-0e7feac20d7d.png)

```python
# make toy trajectory
df = pd.DataFrame([
  {'geometry':Point(0,2), 't':datetime(2018,1,1,12,0,0)},
  {'geometry':Point(6,2), 't':datetime(2018,1,1,12,6,0)},
  {'geometry':Point(6,6), 't':datetime(2018,1,1,12,10,0)},
  {'geometry':Point(9,9), 't':datetime(2018,1,1,12,15,0)},
]).set_index('t')
gdf = GeoDataFrame(df, crs=31256)
toy_traj = mpd.Trajectory(gdf, 1)

## make large polygon
xmin, xmax, ymin, ymax = 0, 5, 0, 5
polygon = Polygon([(xmin, ymin), (xmin, ymax), (xmax, ymax), (xmax, ymin), (xmin, ymin)])

## make smaller polygon
xmin2, xmax2, ymin2, ymax2 = 2, 3, 1, 3
smaller_polygon = Polygon([(xmin2, ymin2), (xmin2, ymax2), (xmax2, ymax2), (xmax2, ymin2), (xmin2, ymin2)])

## make extra smaller polygon
xmin3, xmax3, ymin3, ymax3 = 7, 8, 7, 8
extra_polygon = Polygon([(xmin3, ymin3), (xmin3, ymax3), (xmax3, ymax3), (xmax3, ymin3), (xmin3, ymin3)])

# combine into complex polygon shape
#complex_poly = (polygon - smaller_polygon).union(extra_polygon)
complex_poly = polygon - smaller_polygon
complex_poly

complex_polygon_gdf = GeoDataFrame(pd.DataFrame([{'geometry':complex_poly, 'id':1}]), crs=31256)
intersections = toy_traj.clip(complex_poly)
ax = toy_traj.plot()
complex_polygon_gdf.plot(ax=ax, color='lightgray')
intersections.plot(ax=ax, color='red', linewidth=5, capstyle='round')
```

**Comment by EllieBowler** [comment]
Hi @anitagraser - just wondering if there might be a solution for this bug soon? Thanks!

**Comment by anitagraser** [comment]
Currently, we don't have a timeline for this issue. I was hoping for the upcoming MEOS integration that should fix it but this is not advancing as quickly as I initially thought.

**Comment by anitagraser** [comment]
The following test also fails, presumably because both parts of the multipolygon match to the same trajectory segment. 

```
    def test_clip_with_multipolygon2(self):
        polygon = MultiPolygon([
            Polygon([(-1, -1), (-1, 1), (1, 1), (1, -1), (-1, -1)]),
            Polygon([(3, -1), (3, 1), (4, 1), (4, -1), (3, -1)])
        ])
        collection = self.collection.clip(polygon)
        assert len(collection) == 2
        assert collection.trajectories[0].to_linestring().wkt == "LINESTRING (0 0, 1 0)"
        assert collection.trajectories[1].to_linestring().wkt == "LINESTRING (3 0, 4 0)"
```

**Comment by ilyankou** [comment]
Hi @anitagraser 

Just looking into this bug. The problem also appears when a single polygon overlaps with more than 1 trajectory segment:

<img width="404" alt="Screenshot 2024-12-13 at 09 29 48" src="https://github.com/user-attachments/assets/fd86f4af-fc83-45f2-9dd9-671fc4da9eb8" />

It looks like geopandas `.intersection()` produces a geoseries that includes MultiLineStrings for those complex cases (e.g. line overlapping a polygon with holes) [here](https://github.com/movingpandas/movingpandas/blob/9e166297e578672eec393c549665aa29aa4f1e5a/movingpandas/overlay.py#L198):

```python
possible_matches["spatial_intersection"] = possible_matches.intersection(polygon)
```

And then MultiLineStrings get ignored by by `_get_spatiotemporal_ref(row)` ([link](https://github.com/movingpandas/movingpandas/blob/9e166297e578672eec393c549665aa29aa4f1e5a/movingpandas/overlay.py#L12)) which only handles simple LineStrings (see column `spatiotemporal_intersection` below):

<img width="1134" alt="Screenshot 2024-12-13 at 11 26 14" src="https://github.com/user-attachments/assets/84b053b3-539c-4de7-80f4-ced0eb2d8bec" />

One way to fix this would be `.explode()` the output of `possible_matches.intersection(polygon)` before passing it on to     `_get_spatiotemporal_ref`.

**But in that case, we have an index with repeating time series - is that generally ok or best avoided?**

<img width="1136" alt="Screenshot 2024-12-13 at 11 36 41" src="https://github.com/user-attachments/assets/0483686c-e70e-469d-82de-28aeed7842d9" />

But the good news is that it would pass your [test case above](https://github.com/movingpandas/movingpandas/issues/236#issuecomment-2046793191) and looks ok on the example case:

![output2](https://github.com/user-attachments/assets/db68d7c7-2a8e-462b-b5c9-1621d44e1645)

**Comment by anitagraser** [comment]
Thanks for looking into this issue. 

> in that case, we have an index with repeating time series - is that generally ok or best avoided?

Excellent question. I think we should be fine.
