### ISSUE TITLE
Update theme for docs

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#239]
Update the docs design to use the Theme by the [Executable Book Project](https://ebp.jupyterbook.org/) as shown in https://r5py.readthedocs.io/en/stable/notebooks/basic-usage.html

**Comment by raybellwaves** [comment]
Cool. Note: I have no preference. As an FYI Geopandas uses https://pydata-sphinx-theme.readthedocs.io/en/stable/examples/gallery.html (https://github.com/geopandas/geopandas/blob/main/doc/source/conf.py#L147)

**Comment by anitagraser** [comment]
@raybellwaves fyi: I've now implemented pydata-sphinx-theme based on Geopandas' example: https://movingpandas.readthedocs.io/en/main/index.html

Switching to older versions of the docs breaks the links because I had to put the pages into a new subdir "api" to get the menus right. Currently don't the time to look into proper rewrites. So it will probably stay this way.

**Comment by anitagraser** [comment]
Implemented in c94ba06bcfb6d05c6b74983d67c8bfc98ddf124b to fd3cd2b3fb740f7d4c25499419daf8991f288e21
