### ISSUE TITLE
ShapelyDeprecationWarning in trajectory_stop_detector.py

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas#243]
```python
trajc = mpd.StopSplitter(traj).split(
    min_duration=timedelta(hours=3), max_diameter=30, min_length=500
)
trajc

/Users/ray/miniconda3/envs/pydata-miami-2022-talk/lib/python3.8/site-packages/movingpandas/trajectory_stop_detector.py:67: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for index, data in traj.df[traj.get_geom_column_name()].iteritems():
/Users/ray/miniconda3/envs/pydata-miami-2022-talk/lib/python3.8/site-packages/movingpandas/geometry_utils.py:150: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the `geoms` property instead to get the  number of parts of a multi-part geometry.
  if len(geom) == 2:
/Users/ray/miniconda3/envs/pydata-miami-2022-talk/lib/python3.8/site-packages/movingpandas/geometry_utils.py:151: ShapelyDeprecationWarning: __getitem__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  return _measure_distance(geom[0], geom[1], spherical)
```

#### Output of ``movingpandas.show_versions()``

<details>

MovingPandas 0.11.rc1

SYSTEM INFO
-----------
python     : 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:06:49)  [Clang 12.0.1 ]
executable : /Users/ray/miniconda3/envs/pydata-miami-2022-talk/bin/python
machine    : macOS-10.16-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.0
GEOS lib   : /Users/ray/miniconda3/envs/pydata-miami-2022-talk/lib/libgeos_c.dylib
GDAL       : 3.5.2
GDAL data dir: /Users/ray/miniconda3/envs/pydata-miami-2022-talk/share/gdal
PROJ       : 9.0.1
PROJ data dir: /Users/ray/miniconda3/envs/pydata-miami-2022-talk/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.1
pandas     : 1.5.0
fiona      : 1.8.21
numpy      : 1.21.0
shapely    : 1.8.4
rtree      : 1.0.0
pyproj     : 3.4.0
matplotlib : 3.6.0
mapclassify: 2.4.3
geopy      : 2.2.0
holoviews  : 1.15.0
hvplot     : 0.8.1
geoviews   : 1.9.5
stonesoup  : None

</details>

**Comment by Mrvy29** [comment]
Hi there, any way to fix this issue ? I am also getting this while running any plot function such as : 
```
traj.hvplot(line_width=7.0, tiles='StamenTonerBackground')
```
or 
```
traj_gene.plot(column='track', legend=True, figsize=(9,5))
```
In this case it seems to be producing the plot but extremely slowly.
Error I am getting is : 
```
/usr/local/lib/python3.7/dist-packages/pandas/core/dtypes/cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
```

**Comment by anitagraser** [comment]
I think this has been resolved. Please reopen if this is not the case.
