### ISSUE TITLE
update development mode notes

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas#247]
Currently it says something like https://github.com/anitagraser/movingpandas#develop-mode

https://geopandas.org/en/stable/community/contributing.html has a bit more info 

We should probably just point that page rather than updating notes here

**Comment by anitagraser** [comment]
As far as I can see, the GeoPandas page you linked is more similar to our https://github.com/movingpandas/movingpandas/blob/main/CONTRIBUTING.md
