### ISSUE TITLE
create dummy trajectory and trajectory collection

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas#283]
We have something like https://github.com/geopandas/geopandas/tree/main/geopandas/datasets (although see https://github.com/geopandas/geopandas/issues/2751) and/or https://github.com/pandas-dev/pandas/blob/main/pandas/_testing/__init__.py#L508

**Comment by anitagraser** [comment]
Yes, we already have small test data in the tutorials/data directory, so these could be used straight away.

**Comment by raybellwaves** [comment]
We may be able to use the same host as @martinfleis for geopandas datasets (if he allows us)

**Comment by martinfleis** [comment]
Of course it can be part of the same effort! Just keep in mind that the scope of our work in xyzdata (or whatever the name will be) is not to store the data, just to point at them and cache them on a user side for easier use. So if you want to create something, you'll need another space to store it.

**Comment by anitagraser** [comment]
@raybellwaves are you still considering implementing this?
