### ISSUE TITLE
Improve StopDetector / StopSplitter performance

### ISSUE THREAD

**Issue by ghost** [movingpandas/movingpandas#294]
#### Is your feature request related to a problem?

While using of this package I noticed that the `StopSplitter` method runtime is dependent on both its parameters (max_diameter, min_duration) and on the CRS of the provided trajectory. Specifically:

- a smaller max_diameter increases the runtime
- a larger min_duration increases runtime
- a projected CRS reduces runtime

#### Describe the solution you'd like

Ideally I would like to choose the parameters based on the data, and don't take runtime into account. My expectation would be that the runtime of the `StopSplitter` function is not strongly dependent on the thresholds I set.
Additionally, the function could internally re-project to a projected CRS to reduce runtime and re-project back to the original CRS when returning (not sure if that will still provide a performance gain).

#### API breaking implications

N/A

#### Describe alternatives you've considered

N/A

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Example code how I tested the influence of the parameters
%%time
stopdiam = 300  # manually adjusted to the values, 10, 100, 300, 1000
stopdur = td(minutes=30) # manually adjusted to the values, 10, 30, 300, 1000
tripminlen = 300  # Seems to have no effect

# I can't share the contents of full_traj at the moment, but I imagine it's not dependent on the trajectory itself
trjs = mpd.StopSplitter(full_traj).split(max_diameter=stopdiam, min_duration=stopdur, min_length=tripminlen)

# This is how I found that a projected CRS is faster (about 35% reduction in runtime)
%%time
trjs = mpd.StopSplitter(full_traj.to_crs(CRS(28992))).split(max_diameter=stopdiam, min_duration=stopdur, min_length=tripminlen)
```

**Comment by anitagraser** [comment]
Thank you for your message @ba-tno. Your observations are correct but, unfortunately, there are no easy fixes for the observed performance dependencies. 

We are currently investigating the possibility to integrate https://github.com/MobilityDB/PyMEOS in order to delegate computationally heavy tasks to the faster MEOS C++ library.

**Comment by anitagraser** [comment]
@ba-tno would you mind sharing your multiprocessing code? 

Some work in progress improvements to the algorithm: -30% run times so far 

**New**

![image](https://github.com/movingpandas/movingpandas/assets/590385/9a81d9c0-43b6-45ef-b362-acbc00e57655)

**Old** 

![image](https://github.com/movingpandas/movingpandas/assets/590385/aa12bb6b-12a8-40ae-b37a-f1a1426882c3)

**Comment by anitagraser** [comment]
Singlethreaded - 35%
Multithreaded -56%

![image](https://github.com/movingpandas/movingpandas/assets/590385/99b4b878-87c3-4b85-a65b-6d37e8372112)

**Comment by ba-tno** [comment]
> would you mind sharing your multiprocessing code?

It's a bit convoluted, so it's unfortunately not runnable, but this is the gist of it:


```py
import multiprocessing as mp
import config as cfg
import polars as pl
import geopandas as gpd

def polars2traj(poladf: pl.DataFrame) -> mpd.Trajectory:
    df = poladf.to_pandas().set_index("timestamp").sort_index()
    gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(x=df.lon, y=df.lat), crs="epsg:4326")
    full_traj = mpd.Trajectory(gdf.drop(columns=["lat", "lon"]), traj_id=1)
    return full_traj

def split_traj(
    full_traj: mpd.Trajectory,
    stopdiam: int = cfg.stopdiam,
    stopdur: td = td(minutes=cfg.stopminutes),
    tripminlen: int = cfg.tripminlen,
) -> gpd.GeoDataFrame:
    # The stopsplitter works faster on a projected CRS, hence the reprojecting
    trjs = mpd.StopSplitter(full_traj.to_crs(CRS(28992))).split(
        max_diameter=stopdiam, min_duration=stopdur, min_length=tripminlen
    )
    # Concat multiple trajectories into single gdf per object_id and the current month
    traj_gdf = pd.concat({x.id: x.df for x in trjs.trajectories})
    return traj_gdf

def seq_process(df: pl.DataFrame) -> gpd.GeoDataFrame:
    # Convert the Polars dataframe to a trajectory
    ft = polars2traj(df)
    tgdf = split_traj(ft)
    return tgdf

def parallel_process(dfs: list[pl.DataFrame]) -> pd.DataFrame:
    with mp.Pool(processes=cfg.processes) as pool:
        results = []
        for result in pool.map(func=seq_process, iterable=dfs, chunksize=2):
            results.append(result)
    # Vertically concatenate the result of all the different vessels into a single dataframe
    final_df = pd.concat(results, axis=0)
    final_df = final_df.pipe(derive_cols).pipe(simplify_cols)
    return final_df
```

I provide `parallel_process` with a list of Polars Dataframes that each contain a GPS history of a single vehicle.

**Comment by b-a0** [comment]
I've merged my accounts, so I'm still following this, but under a different handle.
