### ISSUE TITLE
date/time consistency and time zone handling

### ISSUE THREAD

**Issue by bamacgabhann** [movingpandas/movingpandas#303]
If you have a question, rather than a bug report, please post in the [discussions](https://github.com/anitagraser/movingpandas/discussions).
Otherwise, please check: 

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of MovingPandas.
- [x] (optional) I have confirmed this bug exists on the main branch of MovingPandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
[Binder link to example](https://mybinder.org/v2/gh/bamacgabhann/PublicTransportTracking/mpd_stop_points?labpath=ptt.ipynb)

#### Problem description

TrajectoryStopDetector is not working for me after updating to 0.15. The problem appears to be with pandas, not mpd, but a change to the mpd code would solve the problem. I've tried this on my Windows machine, WSL Ubuntu on the same machine, and in Binder, so I don't think it's just me, but I can't say that with 100% certainty.

The issue is in the get_stop_points() method of the TrajectoryStopDetector, specifically in converting the timedelta object to total seconds. 
```python
        if len(stops) > 0:
            stop_pts["duration_s"] = (
                stop_pts["end_time"] - stop_pts["start_time"]
            ).dt.total_seconds()
```
This was working with 0.11, but running with 0.15 now produces:

```python
detector = mpd.TrajectoryStopDetector(track)  # track is a mpd.Trajectory - see the Binder link for working example
stationary_points = detector.get_stop_points(min_duration=timedelta(seconds=15), max_diameter=30)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 2
      1 detector = mpd.TrajectoryStopDetector(track)
----> 2 stationary_points = detector.get_stop_points(min_duration=timedelta(seconds=15), max_diameter=30)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/movingpandas/trajectory_stop_detector.py:182, in TrajectoryStopDetector.get_stop_points(self, max_diameter, min_duration)
    179     stop_pts.at[stop.id, "traj_id"] = stop.parent.id
    181 if len(stops) > 0:
--> 182     stop_pts["duration_s"] = (
    183         stop_pts["end_time"] - stop_pts["start_time"]
    184     ).dt.total_seconds()
    185     stop_pts["traj_id"] = stop_pts["traj_id"].astype(type(stop.parent.id))
    187 return stop_pts

File /srv/conda/envs/notebook/lib/python3.9/site-packages/pandas/core/generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/pandas/core/accessor.py:224, in CachedAccessor.__get__(self, obj, cls)
    221 if obj is None:
    222     # we're accessing the attribute of the class, i.e., Dataset.geo
    223     return self._accessor
--> 224 accessor_obj = self._accessor(obj)
    225 # Replace the property with the accessor object. Inspired by:
    226 # https://www.pydanny.com/cached-property.html
    227 # We need to use object.__setattr__ because we overwrite __setattr__ on
    228 # NDFrame
    229 object.__setattr__(obj, self._name, accessor_obj)

File /srv/conda/envs/notebook/lib/python3.9/site-packages/pandas/core/indexes/accessors.py:580, in CombinedDatetimelikeProperties.__new__(cls, data)
    577 elif is_period_dtype(data.dtype):
    578     return PeriodProperties(data, orig)
--> 580 raise AttributeError("Can only use .dt accessor with datetimelike values")

AttributeError: Can only use .dt accessor with datetimelike values
```
The problem [does appear](https://github.com/pandas-dev/pandas/issues/46582) to be with pandas, specifically that the .dt accessor is not recognising timedelta (and other similar) objects as datetime-like values.

However, upstream issue or not, it still isn't working for me - and if it's not just me, it might not be ideal to leave this broken until pandas fixes .dt handling of timedeltas, especially since they're concentrating on the pyarrow backend right now (which doesn't handle timedeltas either: https://github.com/pandas-dev/pandas/issues/52284).

#### Expected Output

df with "duration_s" column in seconds

#### Fix

The Binder link above takes you to a branch of a repo I'm working on where I've left the error un-fixed. I have fixed it on main in that repo - a very dirty fix where I threw in a .py with a subclass of TrajectoryStopDetector and a working version of the get_stop_points method.

I will happily submit a pull request, if you like. My fix is to change

```python
        if len(stops) > 0:
            stop_pts["duration_s"] = (
                stop_pts["end_time"] - stop_pts["start_time"]
            ).dt.total_seconds()
```
to
```python
        if len(stops) > 0:
            stop_pts["duration_s"] = (
                stop_pts["end_time"] - stop_pts["start_time"]
            )
            stop_pts["duration_s"] = stop_pts["duration_s"].apply(lambda x: x.seconds)
```
[Binder link to ipynb in working repo branch](https://mybinder.org/v2/gh/bamacgabhann/PublicTransportTracking/main?labpath=ptt.ipynb)
[Link to Repo](https://github.com/bamacgabhann/PublicTransportTracking/)

#### Output of ``movingpandas.show_versions()``

<details>

MovingPandas 0.15.rc1

SYSTEM INFO
-----------
python     : 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
executable : /home/breandan/miniconda3/envs/ptt/bin/python
machine    : Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.6.3
GDAL data dir: /home/breandan/miniconda3/envs/ptt/share/gdal
PROJ       : 9.1.1
PROJ data dir: /home/breandan/miniconda3/envs/ptt/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
pandas     : 2.0.0
fiona      : 1.9.2
numpy      : 1.23.5
shapely    : 2.0.1
rtree      : 1.0.1
pyproj     : 3.5.0
matplotlib : 3.7.1
mapclassify: 2.5.0
geopy      : 2.3.0
holoviews  : 1.15.4
hvplot     : 0.8.3
geoviews   : 1.9.6
stonesoup  : 0.1b12

</details>

**Comment by anitagraser** [comment]
Thank you for reporting and also providing a solution. I'm a bit surprised because the TrajectoryStopDetector tests are not failing because our CI is also using Pandas 2.0 now ... 
I assume the tests fail on your local machine?

**Comment by bamacgabhann** [comment]
So this is interesting. The problem is actually handling of date/time data with time zone info. 

I ran the tests, and they pass. I ran some of the tests using my data, and it failed with the same ```AttributeError: Can only use .dt accessor with datetimelike values``` error. I know all my data is sound, it works for everything else, so I broke the TrajectoryStopDetector down to individual lines in a notebook, and using the test test_traj, I get:
```
>>>stop_pts.dtypes  # test_traj
geometry             geometry
start_time     datetime64[ns]
end_time       datetime64[ns]
traj_id               float64
duration_s    timedelta64[ns]
dtype: object

>>>stop_pts.iat[0,4]  # That's stop_pts["duration_s"]
Timedelta('0 days 00:00:04')

>>>stop_pts.iat[0,1]  # That's stop_pts["start_time"]
Timestamp('1970-01-01 00:00:02')

```
But using my data, I get:
```
>>>stop_pts.dtypes  # my data
geometry      geometry
start_time      object
end_time        object
traj_id        float64
duration_s      object
dtype: object

>>>stop_pts.iat[0,4]  # That's stop_pts["duration_s"]
datetime.timedelta(seconds=844)

>>>stop_pts.iat[0,1]  # That's stop_pts["start_time"]
datetime.datetime(2023, 3, 9, 8, 11, 41, tzinfo=datetime.timezone.utc)

```

So it seems like the ```get_stop_points()``` call to pd.Series.dt.total_seconds() can only handle Numpy Timestamp/Timedelta, not standard library datetime.datetime/datetime.timedelta. Note the tzinfo=datetime.timezone.utc there.

Here's the really curious thing though. On trajectory creation, my data **is** a Numpy datetime64[ns] Timestamp:
```
>>>traj.df.index
DatetimeIndex(['2023-03-09 08:11:41+00:00', '2023-03-09 08:11:42+00:00',
               '2023-03-09 08:11:43+00:00', '2023-03-09 08:11:44+00:00',
               '2023-03-09 08:11:45+00:00', '2023-03-09 08:11:46+00:00',
               '2023-03-09 08:11:47+00:00', '2023-03-09 08:11:48+00:00',
               '2023-03-09 08:11:49+00:00', '2023-03-09 08:11:50+00:00',
               ...
               '2023-03-09 09:32:24+00:00', '2023-03-09 09:32:25+00:00',
               '2023-03-09 09:32:26+00:00', '2023-03-09 09:32:27+00:00',
               '2023-03-09 09:32:28+00:00', '2023-03-09 09:32:29+00:00',
               '2023-03-09 09:32:31+00:00', '2023-03-09 09:32:32+00:00',
               '2023-03-09 09:32:33+00:00', '2023-03-09 09:32:34+00:00'],
              dtype='datetime64[ns, UTC]', name='time', length=4788, freq=None)
```

Turns out, my data's date and time got converted from NumPy Timestamp to standard library datetime.datetime while doing TrajectoryStopDetector.get_stop_points():

```
for stop in stops:
    stop_pts.at[stop.id, "start_time"] = stop.get_start_time()
    stop_pts.at[stop.id, "end_time"] = stop.get_end_time()
```
Still a Numpy Timestamp here:

```
>>>stops = TrajectoryCollection(convert_time_ranges_to_segments(traj, stop_time_ranges))
>>>for traj in stops:
    print(traj.df.index.dtype)
datetime64[ns, UTC]
datetime64[ns, UTC]
datetime64[ns, UTC]
datetime64[ns, UTC]
datetime64[ns, UTC]
# 59 times
```

But while creating the 'stop_pts' df:

```
>>>for stop in stops:
    stop_pts.at[stop.id, "start_time"] = stop.get_start_time()
    stop_pts.at[stop.id, "end_time"] = stop.get_end_time()
    pt = Point(stop.df.geometry.x.median(), stop.df.geometry.y.median())
    stop_pts.at[stop.id, "geometry"] = pt
    stop_pts.at[stop.id, "traj_id"] = stop.parent.id

>>>stop_pts["start_time"].apply(type)
stop_id
1_2023-03-09 08:11:41+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:25:47+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:34:20+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:34:54+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:38:07+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:38:34+00:00    <class 'datetime.datetime'>
1_2023-03-09 08:39:03+00:00    <class 'datetime.datetime'>
# 59 times
```
That's in trajectory.py:

```
    def get_start_time(self):
        """
        Return the trajectory's start time.

        Returns
        -------
        datetime.datetime
            Trajectory start time
        """
        return self.df.index.min().to_pydatetime()
```

But oddly that doesn't happen to the test data. 

```
>>>stop_pts["start_time"].apply(type)
stop_id
1_1970-01-01 00:00:02    <class 'pandas._libs.tslibs.timestamps.Timesta...

```

However, if we add timezone info to the test data by:

```
def make_traj2(nodes, crs=CRS_METRIC, id=1, parent=None):
    nodes = [node.to_dict() for node in nodes]
    df = pd.DataFrame(nodes)
    df["t"] = pd.to_datetime(df["t"], utc=True)
    df = df.set_index("t")
    gdf = GeoDataFrame(df)
    if crs:
        gdf = gdf.set_crs(crs=crs, allow_override=True)
    return Trajectory(gdf, id, parent=parent)

test_traj2 = make_traj2(
            [
                Node(0, 0),
                Node(0, 10, second=1),
                Node(0, 20, second=2),
                Node(0, 21, second=4),
                Node(0, 22, second=6),
                Node(0, 30, second=8),
                Node(0, 40, second=10),
                Node(1, 50, second=15),
            ]
        )

>>>test_traj2.df.index
DatetimeIndex(['1970-01-01 00:00:00+00:00', '1970-01-01 00:00:01+00:00',
               '1970-01-01 00:00:02+00:00', '1970-01-01 00:00:04+00:00',
               '1970-01-01 00:00:06+00:00', '1970-01-01 00:00:08+00:00',
               '1970-01-01 00:00:10+00:00', '1970-01-01 00:00:13+00:00',
               '1970-01-01 00:00:15+00:00'],
              dtype='datetime64[ns, UTC]', name='t', freq=None)

>>>stop_time_ranges2 = get_stop_time_ranges(test_traj2, max_diameter, min_duration)
>>>stops2 = TrajectoryCollection(convert_time_ranges_to_segments(test_traj2, stop_time_ranges2))
>>>for traj in stops2:
    print(traj.df.index.dtype)
datetime64[ns, UTC]

>>>stop_pts2 = GeoDataFrame(columns=["geometry"]).set_geometry("geometry")
>>>stop_pts2["stop_id"] = [track.id for track in stops2.trajectories]
>>>stop_pts2 = stop_pts2.set_index("stop_id")
>>>for stop in stops2:
    stop_pts2.at[stop.id, "start_time"] = stop.get_start_time()
    stop_pts2.at[stop.id, "end_time"] = stop.get_end_time()
    pt = Point(stop.df.geometry.x.median(), stop.df.geometry.y.median())
    stop_pts2.at[stop.id, "geometry"] = pt
    stop_pts2.at[stop.id, "traj_id"] = stop.parent.id
>>>stop_pts2["start_time"].apply(type)
stop_id
1_1970-01-01 00:00:02+00:00    <class 'datetime.datetime'>
Name: start_time, dtype: object
```

So, that's the problem. I've tried changing the test data to ```utc=True``` and re-running the tests and a LOT of them fail. I need to look a bit more closely at all of them but I have to run to something now, so it will have to wait until tomorrow. Honestly I'm a little surprised that this hasn't come up as an issue before now, but I guess it was working before pandas 2.0. I think as more people upgrade pandas it will become a much more widespread problem. Without looking at everything, my gut feeling is mpd should try to convert all dates and times to a single format, probably Numpy datetime64[ns] with all datetimes converted to UTC and timezone info dropped. But, movingpandas is yours, not mine! I will undertake to fix this issue though - so if you have a preferred solution, I can implement that, just let me know.

Breandán

**Comment by anitagraser** [comment]
Right. That sounds familiar. In some of the examples, we already had code to drop time zone info: https://github.com/search?q=repo%3Amovingpandas%2Fmovingpandas-examples+tz&type=code

I suggest to 1. add tests with timezone-aware data; 2. dropping timezone info before it causes issues; 3. showing the user a warning that timezone info has been dropped

**Comment by anitagraser** [comment]
plus 4. leave a comment next to the code line that drops timezone info and point to this issue so that future-us knows why we are dropping tz

**Comment by bamacgabhann** [comment]
Will do!

**Comment by bamacgabhann** [comment]
Done and pushed @anitagraser.

1. Timezone info dropped if present when trajectories are created; warning added to alert users if this happens. Comment added to point to this issue for future reference.
2. Test added in test_trajectory.py to check that time zone info is dropped from time zone aware data
3. Test added in test_trajectory_stop_detector.py to make sure the stop detector works with a trajectory created from timezone-aware data.

Let me know if you think anything else is needed for this!
