### ISSUE TITLE
Output unit handling

### ISSUE THREAD

**Issue by bamacgabhann** [movingpandas/movingpandas#308]
### Discussed in https://github.com/movingpandas/movingpandas/discussions/307

<div type='discussions-op-text'>

<sup>Originally posted by **bamacgabhann** May  1, 2023</sup>
1. There are still a couple of methods to return distances which don't use the unit conversions, e.g. ```get_length()``` and ```distance()```. Do any of these need the option to return measurements in different units?
2. I'm wondering if it would be worth changing how DISTANCE_COL_NAME and equivalents work. They seem to be working just fine now, but I wondered about the idea of making them lists, with each new distance etc column appending to the list. Checking for existing columns could then be ```if name in DISTANCE_COL_NAME```. Probably doesn't need to be changed, but just thought I'd make the suggestion.
3. On a related note, default names for distance, speed, acceleration cols could be updated to use units, which would allow declaring units without worrying about names. e.g. someone could to ```traj.get_distance(units="km")``` and the column name could return as "distance (km)". Easy to read the CRS units to have a default if someone just does ```traj.get_distance()```. 

<sup>Originally posted by **anitagraser** May  1, 2023</sup>
1. Thank you for bringing this up. Yes, I think that these methods should also support conversions to different units to be consistent with add_distance, add_speed, and add_acceleration methods.
2. If I understand it correctly, this suggestion would support multiple distance/speed/acceleration columns. Do you have a specific use case in mind that motivates this requirement?
3. Yes, with the introduction of different output units, this could be very helpful for the users to avoid confusion.
</div>

Splitting this part off as suggested, as an issue so that others can be aware of plans to enhance output unit handling. 

1. I will add this to my to-do list (if someone wants to do it before I get there just let me know).
2. I don't have a specific use case in mind for this at present, it just makes me slightly uneasy now that get_distance_col_name() returns only the most recently declared name. But, I don't think anything isn't working as it should. I'll not consider changing it unless something comes up where it's an issue.
3. As for 1, I'll add this to my to-do list.

**Comment by anitagraser** [comment]
Open todos:

- [ ] Automagic column names 
- [ ] Unit support in TrajectoryCollection

**Comment by bamacgabhann** [comment]
I will take both of these on

**Comment by anitagraser** [comment]
@bamacgabhann quick related question: is there a specific reason for the inconsistent writing of meters/metres? If not, I'd switch to meters throughout:

https://github.com/movingpandas/movingpandas/blob/39d5b125ec1b148bb0087b257178f9e631b7c67b/movingpandas/unit_utils.py#L14-L15C56

**Comment by bamacgabhann** [comment]
If I recall correctly it's written differently in some CRS unit descriptions, so in order to match that. I will have some time this week so I'll add double-checking this to my list.

**Comment by anitagraser** [comment]
I've done some work on the unit support and default column names in TrajectoryCollections in https://github.com/movingpandas/movingpandas/commit/847dd9df3c7da14be7686a0b9d63d3eaa6859827 

Is there anything else on the list that needs taking care of before we can close this issue, @bamacgabhann ?

**Comment by anitagraser** [comment]
Please reopen if necessary
