### ISSUE TITLE
DOCS: Small issue with the documentation website - not https compliant

### ISSUE THREAD

**Issue by lwasser** [movingpandas/movingpandas#311]
If you have a question, rather than a bug report, please post in the [discussions](https://github.com/anitagraser/movingpandas/discussions).
Otherwise, please check: 

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of MovingPandas.
- [ ] (optional) I have confirmed this bug exists on the main branch of MovingPandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Problem description

hi @anitagraser 👋 ! i am checking in here as the moving pandas website keeps triggering bad links in our CI build! it's super minor. 
Essentially i think movingpandas.org is not https: compliant meaning it's not secure which is triggering some issues.

The other issue is more related to [pyOpenSci's website blogpost on movingpandas](https://www.pyopensci.org/blog/movingpandas-movement-data-analysis) - there is a binder link that seems to be broken. I'm guessing because you moved the repo to movingpandas as an org? 

<img width="771" alt="Screen Shot 2023-05-04 at 10 35 21 AM" src="https://user-images.githubusercontent.com/7649194/236269699-1e7901e7-f783-481f-9937-d24340a2feed.png">

#### Expected Output

it would be lovely if movingpandas.org was https compliant. i think if it's a github created url you can ensure https with a simple click of that option. And then if you can either submit a pr to update the tutorial binder link or provide it here i can fix that as well. Many thanks!

And i hope you are well!!

**Comment by anitagraser** [comment]
Thank you @lwasser for the heads-up. I'm working on the https ... I think I'm getting closer. *fingers crossed* 

For the blog post, the updated notebook link is: 
https://mybinder.org/v2/gh/movingpandas/movingpandas-examples/main?filepath=1-tutorials/1-getting-started.ipynb
It would be great if you can update it.

**Comment by lwasser** [comment]
ok wonderful! i'll work on that tutorial update and i hope the https works!! many thanks!

**Comment by anitagraser** [comment]
I'm happy to report that https is working now 
![image](https://user-images.githubusercontent.com/590385/236533363-25dee027-e78e-4d60-b14c-5b8c072c5e22.png)
