### ISSUE TITLE
Trajectory.hvplot() error 

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#326]
With a trajectory in epsg:4326, `traj.hvplot(geo=False)` plots the lines correctly, but the arrow-head is on null island.

`traj.hvplot()` results in: 

```
Exception: An axis may only be assigned one projection type

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Path.I   :Path   [Longitude,Latitude]
   .Points.I :Points   [Longitude,Latitude]   (triangle_angle)
```

Can be reproduced with: https://mybinder.org/v2/gh/movingpandas/movingpandas-examples/main?filepath=1-tutorials/1-getting-started.ipynb

**Comment by anitagraser** [comment]
Downgrading from hvplot 0.8.4 to 0.8.3 seems to fix the issue

**Comment by anitagraser** [comment]
Seems related to https://github.com/holoviz/hvplot/issues/1090

**Comment by mathomp4** [comment]
> Downgrading from hvplot 0.8.4 to 0.8.3 seems to fix the issue

Thanks for this. I was going nuts trying to figure out how to run the examples. (I'm not a python dev or anything, just manage the stack others use.)

**Comment by anton-petrov** [comment]
> `traj.hvplot(geo=False)`

Downgrade to 0.8.3 doesn't help unfotunately :( only `traj.hvplot(geo=False)` works

**Comment by anitagraser** [comment]
Looks fine with recent hvplot: 0.10.0 and geoviews: 1.12.0
