### ISSUE TITLE
Add GPS track cleaner

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#333]
We currently have an OutlierCleaner
 https://github.com/movingpandas/movingpandas/blob/dd3ea81949ee45700378a9cb670f1fd67ccd062a/movingpandas/trajectory_cleaner.py#L61-L74

but it doesn't deal well with jumps, e.g. in GPS trajectories. We can apply it recursively on the speed values but this is slow and removes "good" parts of the trajectories, e.g.

![image](https://github.com/movingpandas/movingpandas/assets/590385/57631a9a-b612-4934-90b1-2886b4ba9429)

**Comment by raybellwaves** [comment]
Would jumps have to be smoothed? 
see https://github.com/movingpandas/movingpandas/issues/284

**Comment by anitagraser** [comment]
I'm working on cutting them out: 
![image](https://github.com/movingpandas/movingpandas/assets/590385/35593034-9c09-4493-937e-b92c47c875ec)
