### ISSUE TITLE
Add explore function (like in GeoPandas)

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/movingpandas#360]
#### Is your feature request related to a problem?

Sometimes it can be difficult to install geoviews to get interactive plots

#### Describe the solution you'd like

Since GeoPandas already ships with interactive plots using folium, I'd like to see an .explore() function in MovingPandas as well https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html

#### API breaking implications

None

#### Describe alternatives you've considered

None, since this is the only interactive plotting provided via GeoPandas functions.

#### Additional context

Maybe something as simple as:

```python
tc.to_line_gdf().explore()
```

**Comment by anitagraser** [comment]
This needs upstream handling of datetime columns / indexes, see https://github.com/geopandas/geopandas/pull/3094#event-11360263603

**Comment by martinfleis** [comment]
@anitagraser do you have a preference how datetime columns should be serialised for folium use case? Is a simple string of that okay for movingpandas?

**Comment by anitagraser** [comment]
@martinfleis Yes, i think simple strings would do just fine. Thanks

**Comment by anitagraser** [comment]
Note to self: this is pending the GeoPandas 1.0 release

**Comment by anitagraser** [comment]
Still trying to figure out if this works now: https://github.com/movingpandas/movingpandas/blob/explore/tutorials/0-debug.ipynb

**Comment by anitagraser** [comment]
It works after resetting the index

![image](https://github.com/movingpandas/movingpandas/assets/590385/e459a69d-107e-40e2-ab41-ba61c5200f4b)

**Comment by anitagraser** [comment]
`intersections.add_speed(overwrite=True).to_point_gdf().reset_index().explore(column='speed', vmax=20, tiles="CartoDB positron")`

![image](https://github.com/movingpandas/movingpandas/assets/590385/bb1792a6-296e-436b-819f-4ffb120cf005)

**Comment by martinfleis** [comment]
@anitagraser will not be needed with https://github.com/geopandas/geopandas/pull/3360. Thanks for the report!
