### ISSUE TITLE
Make TrajectoryCollection indexable

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas#365]
Give a TrajectoryCollection you can index it using `traj_collection.get_trajectory(traj_id_col VALUE)`.

I would like to be able to do traj_collection[0] which would do unique traj_id_col VALUES[0].

This will get a bit tricky if you have values "z", "y", "x". Should 0 return "x" or "z".

Either way I think mostly for exploration whatever the order of .unique() returns can be used. `get_trajectory` should still be encouraged but I feel a `__getitem__` will help with quick exploration

**Comment by anitagraser** [comment]
Hi Ray. Could you elaborate how this differs from TrajectoryCollection.tajectories[0]

An example would be great to help me understand
