### ISSUE TITLE
Add TrajectoryCollection.get_trajectories(object_id): TrajectoryCollection method 

### ISSUE THREAD

**Issue by raybellwaves** [movingpandas/movingpandas#367]
I'm thinking a get_trajectories method takes a obj_id_col value and returns trajectories for that obj_id_col value

**Comment by anitagraser** [comment]
Is this not covered by https://movingpandas.readthedocs.io/en/main/trajectorycollection.html#movingpandas.TrajectoryCollection.get_trajectory ?
