### ISSUE TITLE
Add functionality to split trajectory based on change in angle/heading

### ISSUE THREAD

**Issue by Naarlack** [movingpandas/movingpandas#370]
#### Is your feature request related to a problem?

I'm playing around with some routing and map matching. Based on my experiments so far, it helps to split trajectories into smaller segments at points where the heading/angle changes significantly - i.e. where a turn has been made.

#### Describe the solution you'd like

It would be great to have a new splitter class that achieves this. Something like HeadingSplitter or AngleChangeSplitter. Other than splitting at a different feature, it could work just like all the other splitters. 

#### API breaking implications

No issues that I can think of.

#### Describe alternatives you've considered

I have achieved this previously in native GeoPandas and would be happy to provide that as a starting point.

#### Additional context

There may be some issues I'm yet to think through. My previous efforts used GPS data collected from a vehicle. I had to ignore any data where the speed was below a certain threshold (indicating a stop) as this produced GPS drift and constant spurious heading changes. Perhaps some of the current StopSplitter functionality could be applied.

**Comment by anitagraser** [comment]
It might be worth looking into the trajectory aggregator code, where it computes the significant points. Those should be at direction or speed changes

**Comment by Naarlack** [comment]
Ah yes, I should have noticed that since I've been digging around in the aggregator. 

Do you mind if I have a go at building a `AngleChangeSplitter` class, building off that aggregator code?

**Comment by anitagraser** [comment]
Feel free to give it a go.

**Comment by Naarlack** [comment]
I'm getting to a point where I need to make a crucial decision and I'm not sure whether there is a "movingpandas" policy on such things...

When splitting a trajectory there are two possible ways that I can see:

1) All original points be retained only once.
So (0 0, 1 1, 2 2, 3 3) would become (0 0, 1 1) and (2 2, 3 3).
The current splitter classes seem to follow this method but it means you lose the link between (1 1, 2 2).

2) All links between points are retained.
So (0 0, 1 1, 2 2, 3 3) would become (0 0, 1 1) and (1 1, 2 2, 3 3).
However, this means the (1 1) data point is repeated.

An alternative to making a hard choice would be to add a flag to the splitter classes so the user can decide what behaviour they would like.

**Comment by anitagraser** [comment]
For the AngleChangeSplitter, I can definitely see that splitting at the point of angle change and retaining all links makes sense. This should probably be the default. Not sure if the flag is necessary.

**Comment by anitagraser** [comment]
PR here:  https://github.com/movingpandas/movingpandas/pull/371
