### ISSUE TITLE
Add summary data to TrajectoryCollection

### ISSUE THREAD

**Issue by Naarlack** [movingpandas/movingpandas#373]
#### Is your feature request related to a problem?

It would be nice for a TrajectoryCollection to provide some useful summary statistics. For example (but not necessarily limited to, or all required):

- Total length
- Average length
- Total time
- Average time
- Average speed
- Average acceleration
- Average direction

These call all be obtained by iterating through the TrajectoryCollection, and probably should be if you are after something precise, but that can take a significant amount of time if you just want to be exploring the data.

#### Describe the solution you'd like

I think these summary statistic could be generated at the same time as the TrajectoryCollection is being generated. Then it would just need methods that expose the data, such as `TrajectoryCollection.total_length()`.

#### API breaking implications

No issues I'm aware of.

#### Describe alternatives you've considered

Just iterating through each trajectory manually.

**Comment by anitagraser** [comment]
Please give the export function `TrajectoryCollection.to_traj_gdf` a try. It provides flexible aggregation support for arbitrary columns, e.g.

```
tc.add_speed()
tc.to_traj_gdf(agg={'speed':['mean','max']})
```

![image](https://github.com/movingpandas/movingpandas/assets/590385/0d84f66b-6858-435e-8c68-436a4033973f)

**Comment by anitagraser** [comment]
Please share (open feature requests or start a thread in the forums) if you identify any gaps in this approach. 

I prefer to stay away from precomputing the values when creating the TrajectoryCollection since that would require to keep the values in sync at every processing step.

**Comment by Naarlack** [comment]
> I prefer to stay away from precomputing the values when creating the TrajectoryCollection since that would require to keep the values in sync at every processing step.

Good point - I didn't think of that!

Thanks for responding.

Your suggestion works, but I still find it is very slow. Not much different in terms of speed than manually iterating through each trajectory.

I have a collection of around 2,000 trajectories and running `tc.to_traj_gdf()["length"].sum()` takes quite a while. Maybe that's to be expected?

I'll play around a bit more and get some examples to the forums if I get anywhere 😁

**Comment by anitagraser** [comment]
Multithreading should help speed up things if you want to try implement that.
