### ISSUE TITLE
FutureWarning: Dask dataframe query planning is disabled because dask-expr is not installed in movingpandas

### ISSUE THREAD

**Issue by mar3021** [movingpandas/movingpandas#396]
#### Is your feature request related to a problem?
When running "movingpandas.show_versions()":

FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

#### Describe the solution you'd like
No FutureWarning with Dask

#### Describe alternatives you've considered
Installing Dask

**Comment by raybellwaves** [comment]
If you want to remove that warning, install dask.

It is not worth adding a large dependency to remove one warning
