### ISSUE TITLE
Drop Fiona dependency

### ISSUE THREAD

**Issue by owenlamont** [movingpandas/movingpandas#417]
#### Is your feature request related to a problem?

Since you've updated to GeoPandas 1.0 which has dropped it's Fiona dependency I was wondering if MovingPandas can now also drop it's dependency on Fiona too (MovingPandas is barely using it directly and I assume there's alternative APIs you could use in the one or two places you do touch it).

#### Describe the solution you'd like

Drop the dependency on Fiona

#### API breaking implications

I don't think this will require any breaking changes

#### Describe alternatives you've considered

You can continue to depend on it but I think it is practically superfluous and isn't used by your main dependency GeoPandas anymore.

#### Additional context

[GeoPandas 1.0 moving from fiona to pygrio](https://geopandas.org/en/latest/docs/user_guide/fiona_to_pyogrio.html)

**Comment by anitagraser** [comment]
A quick test shows some issues: https://github.com/movingpandas/movingpandas/actions/runs/11382634736/job/31666555199?pr=423

**Comment by anitagraser** [comment]
The conclusion seems to be that we can drop fiona in favor of pyogrio
