### ISSUE TITLE
get_start_locations() has no CRS

### ISSUE THREAD

**Issue by mar3021** [movingpandas/movingpandas#425]
#### Code Sample, a copy-pastable example

```python
tc = mpd.TrajectoryCollection(
        gdf,
        traj_id_col=TRAJ_ID,
        obj_id_col=MOVER_ID,
        t=TIMESTAMP,
        x="x",
        y="y",
        crs="epsg:4326",
    )

start = tc.get_start_locations()
```

```python
trajs = data.to_trajs()
start = trajs.get_start_locations()
```

#### Problem description
gdf has no CRS after performing get_start_locations(). Likely same issue with get_end_locations(). The AISDK class was applied to the data beforehand and it is possible that the AISDK class does not set the CRS correctly. Please see image:
![image](https://github.com/user-attachments/assets/c6e6a407-3e13-4a23-b19b-86b00f31a76b)

#### Expected Output
get_start_locations() should set a CRS or keep the CRS set previously. 

#### Output of ``movingpandas.show_versions()``

<details>

MovingPandas 0.18.1

SYSTEM INFO
-----------
python     : 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
executable : /home/mar3021/miniforge3/envs/movingml/bin/python
machine    : Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.9.1
PROJ       : 9.4.0

PYTHON DEPENDENCIES
-------------------
geopandas  : 1.0.1
pandas     : 2.2.2
fiona      : 1.9.6
numpy      : 2.1.2
shapely    : 2.0.4
rtree      : 1.2.0
pyproj     : 3.6.1
matplotlib : 3.8.4
mapclassify: 2.6.1
geopy      : 2.4.1
holoviews  : 1.17.1
hvplot     : None
geoviews   : None
stonesoup  : None

</details>

**Comment by anitagraser** [comment]
Issue confirmed
