### ISSUE TITLE
Hover functionality not working when hover_cols attribute  is used in hvplot

### ISSUE THREAD

**Issue by Vikas-Singh-Negi** [movingpandas/movingpandas#91]
Hi There

I am trying to make use of hover option of hvplot to reflect speed /any column available in trajectory(my_traj) in the tutorial in repo, but it does not show anything while hovering

my_traj = traj_collection.trajectories[1]

my_traj.hvplot(c='speed',hover_cols=['speed'],width=700, height=400, line_width=7.0, tiles='StamenTonerBackground', cmap='Viridis', colorbar=True, clim=(0,20))
 
I am a newbie in both python and Data visualization,so Please pardon me if in case it comes out as a silly question.

**Comment by anitagraser** [comment]
I can reproduce the issue in some setups but not others. Seems to depend on other library versions. I'll have to investigate.

**Comment by anitagraser** [comment]
Seems related to #71

**Comment by anitagraser** [comment]
I think this has been resolved in the meantime.
